# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6.10

    working_directory: ~/aws-demos

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      # Install AWS CLI
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            set -x
            echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update
            sudo apt-get install ansible -y

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

      - deploy:
          name: Run Playbook if in master branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export ANSIBLE_HOST_KEY_CHECKING=False
              ansible-playbook -i ~/aws-demos/3_Ansible/hosts ~/aws-demos/3_Ansible/playbook.yml -u ec2-user
            else
              echo "Not master branch so not deploying!"
            fi
